### ISSUE TITLE
mgoquery.parse should support number or boolean values

### ISSUE THREAD

**Issue by janeto** [ToMMApps/mgoqueryjs#1]
We are now using the library. It is very helpful. Thanks.
I think the library will be much useful if it extends to support of parsing number or boolean values.
E.g: `flag=true`, `number > 10`
As of now, It is returning `null`.

Thanks!

**Comment by henning96** [comment]
You're right! That would be very helpful. And I think I have a solution.
I have experimented a little with the grammar file and now the parser does this:
x=2 => {'x': 2}
x>2 =>  {'x': {'$gte': 2}}
x='2' => {'x': '2'}
x=true => {'x': true}
x=false => {'x': false}

That should do the job.

**Comment by janeto** [comment]
Thanks! It is exact What we need.

**Comment by henning96** [comment]
Great! I will write some tests and then upload the stuff.
